"""
Invoice Generator - Generate billing invoices.
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, date
from pathlib import Path
from typing import Dict, List, Optional
import aiofiles

from .tracker import BillingTracker, UsageRecord

logger = logging.getLogger(__name__)


@dataclass
class InvoiceLineItem:
    """A line item on an invoice"""
    description: str
    quantity: int
    unit: str
    rate: float
    amount: float

    def to_dict(self) -> Dict:
        return {
            "description": self.description,
            "quantity": self.quantity,
            "unit": self.unit,
            "rate": self.rate,
            "amount": self.amount,
        }


@dataclass
class Invoice:
    """A billing invoice"""
    invoice_id: str
    client_id: str
    period_start: date
    period_end: date
    generated_at: datetime
    line_items: List[InvoiceLineItem] = field(default_factory=list)
    subtotal: float = 0.0
    tax_rate: float = 0.0
    tax_amount: float = 0.0
    total: float = 0.0
    notes: Optional[str] = None
    status: str = "draft"  # draft, sent, paid

    def to_dict(self) -> Dict:
        return {
            "invoice_id": self.invoice_id,
            "client_id": self.client_id,
            "period_start": self.period_start.isoformat(),
            "period_end": self.period_end.isoformat(),
            "generated_at": self.generated_at.isoformat(),
            "line_items": [item.to_dict() for item in self.line_items],
            "subtotal": self.subtotal,
            "tax_rate": self.tax_rate,
            "tax_amount": self.tax_amount,
            "total": self.total,
            "notes": self.notes,
            "status": self.status,
        }

    def to_markdown(self) -> str:
        """Generate markdown invoice"""
        md = f"""# INVOICE

**Invoice #**: {self.invoice_id}
**Date**: {self.generated_at.strftime('%Y-%m-%d')}
**Status**: {self.status.upper()}

---

**Bill To**: {self.client_id}

**Period**: {self.period_start} to {self.period_end}

---

## Line Items

| Description | Quantity | Unit | Rate | Amount |
|-------------|----------|------|------|--------|
"""
        for item in self.line_items:
            md += f"| {item.description} | {item.quantity:,} | {item.unit} | ${item.rate:.4f} | ${item.amount:.4f} |\n"

        md += f"""
---

**Subtotal**: ${self.subtotal:.4f}
"""
        if self.tax_rate > 0:
            md += f"**Tax ({self.tax_rate*100:.1f}%)**: ${self.tax_amount:.4f}\n"

        md += f"""
## **TOTAL**: ${self.total:.4f}

---
"""
        if self.notes:
            md += f"\n*{self.notes}*\n"

        md += f"""
Generated by ABLE Billing System
{self.generated_at.isoformat()}
"""
        return md


class InvoiceGenerator:
    """
    Generate invoices from usage data.

    Supports:
    - Period-based invoicing
    - Multiple output formats (JSON, Markdown)
    - Draft/Send/Paid workflow
    """

    def __init__(self, tracker: BillingTracker, invoices_path: Path):
        self.tracker = tracker
        self.invoices_path = Path(invoices_path)
        self.invoices_path.mkdir(parents=True, exist_ok=True)

    async def generate(
        self,
        client_id: str,
        period_start: date,
        period_end: date,
        tax_rate: float = 0.0,
        notes: Optional[str] = None
    ) -> Invoice:
        """
        Generate an invoice for a client.

        Args:
            client_id: Client to invoice
            period_start: Start of billing period
            period_end: End of billing period
            tax_rate: Tax rate (0.0 to 1.0)
            notes: Additional notes

        Returns:
            Generated Invoice
        """
        # Get usage data
        start_dt = datetime.combine(period_start, datetime.min.time())
        end_dt = datetime.combine(period_end, datetime.max.time())

        records = await self.tracker._get_records(client_id, start_dt, end_dt)

        if not records:
            logger.warning(f"No usage records for {client_id} in period")

        # Aggregate by provider
        by_provider = {}
        for r in records:
            if r.provider not in by_provider:
                by_provider[r.provider] = {
                    "input_tokens": 0,
                    "output_tokens": 0,
                    "cost": 0.0,
                }
            by_provider[r.provider]["input_tokens"] += r.input_tokens
            by_provider[r.provider]["output_tokens"] += r.output_tokens
            by_provider[r.provider]["cost"] += r.cost

        # Create line items
        line_items = []

        for provider, data in by_provider.items():
            # Input tokens line
            if data["input_tokens"] > 0:
                line_items.append(InvoiceLineItem(
                    description=f"{provider.capitalize()} - Input tokens",
                    quantity=data["input_tokens"],
                    unit="tokens",
                    rate=self.tracker.client_rates["input_per_million"] / 1_000_000,
                    amount=data["input_tokens"] * self.tracker.client_rates["input_per_million"] / 1_000_000
                ))

            # Output tokens line
            if data["output_tokens"] > 0:
                line_items.append(InvoiceLineItem(
                    description=f"{provider.capitalize()} - Output tokens",
                    quantity=data["output_tokens"],
                    unit="tokens",
                    rate=self.tracker.client_rates["output_per_million"] / 1_000_000,
                    amount=data["output_tokens"] * self.tracker.client_rates["output_per_million"] / 1_000_000
                ))

        # Calculate totals
        subtotal = sum(item.amount for item in line_items)
        tax_amount = subtotal * tax_rate
        total = subtotal + tax_amount

        # Create invoice
        invoice_id = f"INV-{client_id}-{period_end.strftime('%Y%m%d')}"

        invoice = Invoice(
            invoice_id=invoice_id,
            client_id=client_id,
            period_start=period_start,
            period_end=period_end,
            generated_at=datetime.utcnow(),
            line_items=line_items,
            subtotal=subtotal,
            tax_rate=tax_rate,
            tax_amount=tax_amount,
            total=total,
            notes=notes,
            status="draft"
        )

        # Save invoice
        await self._save_invoice(invoice)

        logger.info(f"Generated invoice {invoice_id}: ${total:.4f}")

        return invoice

    async def _save_invoice(self, invoice: Invoice):
        """Save invoice to disk"""
        # JSON format
        json_path = self.invoices_path / f"{invoice.invoice_id}.json"
        async with aiofiles.open(json_path, 'w') as f:
            await f.write(json.dumps(invoice.to_dict(), indent=2))

        # Markdown format
        md_path = self.invoices_path / f"{invoice.invoice_id}.md"
        async with aiofiles.open(md_path, 'w') as f:
            await f.write(invoice.to_markdown())

    async def mark_sent(self, invoice_id: str):
        """Mark invoice as sent"""
        await self._update_status(invoice_id, "sent")

    async def mark_paid(self, invoice_id: str):
        """Mark invoice as paid"""
        await self._update_status(invoice_id, "paid")

    async def _update_status(self, invoice_id: str, status: str):
        """Update invoice status"""
        json_path = self.invoices_path / f"{invoice_id}.json"
        if not json_path.exists():
            raise ValueError(f"Invoice not found: {invoice_id}")

        async with aiofiles.open(json_path, 'r') as f:
            data = json.loads(await f.read())

        data["status"] = status

        async with aiofiles.open(json_path, 'w') as f:
            await f.write(json.dumps(data, indent=2))

        logger.info(f"Invoice {invoice_id} marked as {status}")

    async def list_invoices(
        self,
        client_id: Optional[str] = None,
        status: Optional[str] = None
    ) -> List[Dict]:
        """List all invoices, optionally filtered"""
        invoices = []

        for path in self.invoices_path.glob("*.json"):
            async with aiofiles.open(path, 'r') as f:
                data = json.loads(await f.read())

                if client_id and data["client_id"] != client_id:
                    continue
                if status and data["status"] != status:
                    continue

                invoices.append(data)

        # Sort by date, most recent first
        invoices.sort(key=lambda x: x["period_end"], reverse=True)

        return invoices
