#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  ABLE Installer — one command to get `able chat` working
#
#  Usage:
#    bash install.sh          # from inside the ABLE repo
#    curl -sL <url> | bash    # remote install (future)
# ═══════════════════════════════════════════════════════════════

set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
SHELL_RC=""

# ── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "  ${GREEN}✓${NC} $1"; }
warn()  { echo -e "  ${YELLOW}⚠${NC} $1"; }
fail()  { echo -e "  ${RED}✗${NC} $1"; exit 1; }

echo ""
echo -e "${BOLD}  ABLE Installer${NC}"
echo "  ─────────────────────────────────"

# ── 1. Check / install Python ─────────────────────────────────
PYTHON=""
for candidate in python3.14 python3.13 python3.12 python3.11 python3; do
    if command -v "$candidate" &>/dev/null; then
        ver=$("$candidate" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+')
        major=$(echo "$ver" | cut -d. -f1)
        minor=$(echo "$ver" | cut -d. -f2)
        if [ "$major" -ge 3 ] && [ "$minor" -ge 11 ]; then
            PYTHON="$candidate"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    warn "Python 3.11+ not found."
    if command -v brew &>/dev/null; then
        echo "  Installing Python via Homebrew..."
        brew install python@3.13
        PYTHON="python3.13"
    elif command -v apt-get &>/dev/null; then
        echo "  Installing Python via apt..."
        sudo apt-get update -qq && sudo apt-get install -y -qq python3 python3-venv python3-pip
        PYTHON="python3"
    elif command -v dnf &>/dev/null; then
        echo "  Installing Python via dnf..."
        sudo dnf install -y python3 python3-pip
        PYTHON="python3"
    else
        fail "Cannot auto-install Python. Install Python 3.11+ manually, then re-run."
    fi
fi

info "Python: $($PYTHON --version)"

# ── 2. Create virtual environment ─────────────────────────────
if [ ! -d "$VENV_DIR" ]; then
    echo "  Setting up environment..."
    "$PYTHON" -m venv "$VENV_DIR"
    info "Virtual environment created"
else
    info "Virtual environment exists"
fi

# ── 3. Install dependencies + ABLE package ────────────────────
echo "  Installing dependencies (this may take a minute)..."
"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet -r "$REPO_DIR/able/requirements.txt"
"$VENV_DIR/bin/pip" install --quiet -e "$REPO_DIR"
info "ABLE installed"

# ── 4. Verify the package imports outside the repo root ───────
if ! (cd /tmp && "$VENV_DIR/bin/python" -c "import sys; sys.path.insert(0, '$REPO_DIR'); import able" >/dev/null 2>&1); then
    fail "Installation failed — the ABLE package could not be imported"
fi

# ── 5. Create a global wrapper script ─────────────────────────
#    This lets `able` work from ANY terminal without activating the venv.
WRAPPER_DIR="$HOME/.local/bin"
WRAPPER="$WRAPPER_DIR/able"
CHAT_WRAPPER="$WRAPPER_DIR/able-chat"
mkdir -p "$WRAPPER_DIR"

cat > "$WRAPPER" << WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated by ABLE installer — delegates to the repo-backed venv Python
export PYTHONPATH="$REPO_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$VENV_DIR/bin/python" -m able "\$@"
WRAPPER_EOF
chmod +x "$WRAPPER"

cat > "$CHAT_WRAPPER" << WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated by ABLE installer — repo-backed chat entrypoint
export PYTHONPATH="$REPO_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$VENV_DIR/bin/python" -m able chat "\$@"
WRAPPER_EOF
chmod +x "$CHAT_WRAPPER"
info "Command installed: $WRAPPER"

# ── 6. Ensure ~/.local/bin is on PATH ─────────────────────────
if ! echo "$PATH" | tr ':' '\n' | grep -q "$WRAPPER_DIR"; then
    # Detect shell rc file
    if [ -n "$ZSH_VERSION" ] || [ "$(basename "$SHELL")" = "zsh" ]; then
        SHELL_RC="$HOME/.zshrc"
    elif [ -f "$HOME/.bashrc" ]; then
        SHELL_RC="$HOME/.bashrc"
    elif [ -f "$HOME/.bash_profile" ]; then
        SHELL_RC="$HOME/.bash_profile"
    fi

    if [ -n "$SHELL_RC" ]; then
        if ! grep -q '\.local/bin' "$SHELL_RC" 2>/dev/null; then
            echo '' >> "$SHELL_RC"
            echo '# ABLE' >> "$SHELL_RC"
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
            info "Added ~/.local/bin to PATH in $SHELL_RC"
        else
            info "~/.local/bin already in $SHELL_RC"
        fi
    fi
    export PATH="$WRAPPER_DIR:$PATH"
fi

# ── 7. Initialize ~/.able workspace if needed ─────────────────
ABLE_HOME="${ABLE_HOME:-$HOME/.able}"
if [ ! -d "$ABLE_HOME" ]; then
    bash "$REPO_DIR/scripts/able-setup.sh" 2>/dev/null || true
    info "Workspace initialized at $ABLE_HOME"
else
    info "Workspace exists at $ABLE_HOME"
fi

# ── 8. Federation identity ──────────────────────────────────────
"$VENV_DIR/bin/python3" -c "from able.core.federation.identity import get_or_create_instance_id; get_or_create_instance_id()" 2>/dev/null || true

# ── Done ──────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}  Done!${NC} Run these commands:"
echo ""
echo -e "    ${GREEN}able chat${NC}              # start chatting"
echo -e "    ${GREEN}able chat --verbose${NC}    # with full logs"
echo -e "    ${GREEN}able serve${NC}             # start the service"
echo ""
if [ -n "$SHELL_RC" ]; then
    echo -e "  ${YELLOW}Restart your terminal${NC} or run: source $SHELL_RC"
    echo ""
fi
